### ISSUE TITLE
Not working with Star Citizen

### ISSUE THREAD

**Issue by gutsanglory** [Codeusa/Borderless-Gaming#100]
Used the 6.5 version before, worked great, downloaded new 7 version...does not work with this game any longer. 
Running windows 7 64bit

**Comment by psouza4** [comment]
Like other reports, this is almost certainly fixed by running the shortcut as an Administrator.

**Comment by gutsanglory** [comment]
Yup…I tried that…..still not working.

**Comment by gutsanglory** [comment]
Ok....removed program....
Cleaned up....
Re-installed program as admin....still does not work
Adjust shortcut properties to "run as admin" .....still does not work.
Launch shortcut using the right click context menu "run as admin" ....works fine.

Kinda sucks that you have to run as admin from the context menu every time. The previous version just worked out of the box.

Thx,

**Comment by psouza4** [comment]
Previous versions had an embedded manifest that forced the program to only work when elevated, which means users who didn't want to (or couldn't) give the program administrative rights could not use the program at all.  It also caused issues during installation and it prevented the application from launching at startup under Windows 8/8.1/2012 thanks to changes in how UAC elevation works.  Thus, starting elevated is now optional.

Unfortunately, there's a handful of games out there (mostly games with their own anti-hacking system) that run elevated and Borderless Gaming can't send messages to windowed owned by elevated applications unless it's also elevated.

You may be able to navigate to C:\Program Files (x86)\Borderless Gaming and change the properties of the Borderless Gaming.exe binary to always run as an administrator, instead of the shortcut to the application.

**Comment by gutsanglory** [comment]
nope...does not seem to work....i can go to the .exe file and adjust properties to run as admin, but it still wont work unless i specifically use the right click and run as admin. I dont know the difference between those two..but thats what happens. 
Thanks for you responses...much appreciated
.

**Comment by psouza4** [comment]
I think we'll just have to release two versions of the application -- one that always launches as Administrator (which breaks for some people and especially will break starting with Windows) and one that starts normally that requires you to start as administrator for a few games.

**Comment by gutsanglory** [comment]
New release is working.

THX!

**Comment by karasuhebi** [comment]
@psouza4 & @Codeusa: There's multiple workarounds for being able to autostart on Windows 8/8.1 with elevated privileges. Check out what apps like Fraps do. Basically what you do is have Borderless-Gaming install on C:\ instead of C:\Program Files\ and then schedule a task that runs at log on of any user.

**Comment by regs01** [comment]
> New release is working.
> 
> THX!
It does resize for me, but i can't use mouse. Mouse acts like window is not resized.
