### ISSUE TITLE
Borderlands doesn't work with Borderless Gaming

### ISSUE THREAD

**Issue by karasuhebi** [Codeusa/Borderless-Gaming#125]
It'll try to put it into borderless fullscreen but it'll fail and it'll just stay in a normal window instead. Anything that can be done about this @Codeusa?

**Comment by karasuhebi** [comment]
I just tried it again with v8.2 just to see if it magically fixed itself but it's still a no-go. :(

**Comment by psouza4** [comment]
According to https://en.wikipedia.org/wiki/Borderlands_(video_game)

Borderlands run on Unreal Engine 3.  Borderless Gaming is not compatible with any UE3 game because of UE3's persistence for resetting window properties.

**Comment by karasuhebi** [comment]
Oh I see. Bummer. Is there any plans/hope of working around this in the future? Or is it a solid "no"?

**Comment by psouza4** [comment]
I don't think there's anything we actually can do.  We're telling Windows to change the window properties to not have a caption, border, and resize.  The game is checking its window properties and telling Windows to reset them.  They fight for control back and forth until one side gives up... since Unreal Engine 3 doesn't give up, Borderless Gaming is programmed to do so after 3 attempts.

**Comment by karasuhebi** [comment]
Yeah that's exactly the behavior I'm seeing. I see it try to go back and forth between borderless and bordered. Oh well. :-\

Can you maybe implement an alternative way to do borderless windowed for UE3 games? There's quite a lot of those. Maybe something like what ShiftWindow or Full-Window do?

**Comment by CoenraadS** [comment]
For those who don't feel like browsing through my old (shitty) code, the tl;dr is:

Calculate the titlebar height, and the border size.
Resize the window by those amounts so that it is larger then the monitor, and the client area fits perfectly.

Use the SWP_NOSENDCHANGING flag to stop Borderlands repositioning itself.

I'm not sure my program works on Borderlands anymore, since along the way it broke and I stopped maintaining it, but it used to work using the above method.

**Comment by karasuhebi** [comment]
Thanks for your feedback @CoenraadS, and thanks for putting the Full-Window repo back up. :D

I did however miss out on your reply to my issue in your Cities: Skyline News Ticker repo though, since it looks like you took that down as well. :-\ Would you mind telling me what it was you had replied to me?

**Comment by CoenraadS** [comment]
Pretty much the same thing

**Comment by karasuhebi** [comment]
In the issue I opened up on News Ticker I was asking why you took down the Full-Window repo, I wasn't asking about UE3 games.

**Comment by CoenraadS** [comment]
>Hey, I set the repo to private because there are better alternatives available, and I got frustrated that games that previously worked with my program stopped working in later releases. However I set it to public again, but for now am not working on it and suggest you look here: http://pcgamingwiki.com/wiki/Glossary:Borderless_fullscreen_windowed for alternatives.

**Comment by karasuhebi** [comment]
Sweet thanks. :D

**Comment by psouza4** [comment]
Side note: SWP_NOSENDCHANGING isn't doing anything for UE3 games.  Tried it on A Story About My Uncle and Borderlands 2 and it still reacted to having window properties set.  Thanks for opening your repo though, I'll take a look and see if there's anything we can use and benefit from!

**Comment by iiFirestorm** [comment]
This is a very late response but I felt like it was worth posting in case anyone else stumbled on this thread.

A solution for me has been to remove Borderlands from the list of favorite applications on Borderless Gaming, load it up, and then re-add it. It should stick in borderless fullscreen without any issues. You will have to remove it every time before opening it, which is annoying, but it's the only solution I can find.
