### ISSUE TITLE
Bug: resize causing issues with aspect in some games

### ISSUE THREAD

**Issue by roughnecks** [Codeusa/Borderless-Gaming#134]
Hi there,
I've been trying your app for the last 30 minutes on 2 games: Euro Truck Simulator 2 and Tropico 3.

1) I'm running ETS2 @1600x900 on a widescreen monitor which has 1920x1080 resolution. When I switch to bordeless, the game loses its aspect ratio (the window is too tall to fit into the screen).

2) When running Tropico 3 borderless I lose mouse pointer precision in menus: e.g. If I have to click on the first "button" in the menu, I have to move the pointer several pixel lower to have the button highlighted (clickable). I think that happens because of the titlebar which gets removed by Borderless Gaming, thus resulting in a position mismatch - I say so because the pointer is fine until I switch to borderless.

That's it, thanks for reading.

**Comment by ZwaanME** [comment]
I have a similar problem using Borderless Gaming with games like Empress of the Deep (hidden object game) that run in a low resolution (800x600 or 1024x768). When I run games like these without a border they no longer scale the position of the mouse cursor which makes it almost impossible to play. The middle of my screen is interpreted as the lower right corner making it hard to click buttons. Is there any way to correct this? I can't change the resolution as suggested because these games only run in one resolution setting.

**Comment by psouza4** [comment]
In the future, please divide your issues into separate reports and also check if the issue has previously been reported already.  We can't resolve issues that are bundled together like this.  That said:

(1) For that game, try turning off auto-maximize and set the size manually

(2) Unfortunately, some games behave this way because they don't translate region coordinates smoothly. There's nothing Borderless Gaming can do for these games.

**Comment by roughnecks** [comment]
Sorry for the single post, my bad.

1. I don't get what you're saying. Game is running in a window and there's no such option like auto-maximize; it's Borderless-Gaming which maximizes the game and it does it badly.

2. Got it. It's a shame nonotheless because it makes your app unusable in some games and you have to check for games' compatibility case by case (not my thing).

Best of luck with your projects :)
