### ISSUE TITLE
Not working with Command and Conquer 3 Tiberium Wars

### ISSUE THREAD

**Issue by QuantumGTV** [Codeusa/Borderless-Gaming#152]
Whatever I try (making it borderless, selecting how big the window will be etc) it does not go off full screen. I paid 3+ euro's for this just so I can play this game in window mode. Can someone please tell me how I can make it work?

**Comment by psouza4** [comment]
Add -win to the shortcut/startup parameters for your game, which will force the game in a window.  Then use Borderless Gaming to change the properties as desired.

**Comment by QuantumGTV** [comment]
could you explain to me how I do that? :s

**Comment by karasuhebi** [comment]
Right-click on the shortcut and go to Properties. The new Properties window should open in the "Shortcut" tab. If it doesn't, click on that tab. Now in the "Target" field, type in -win after everything else that's already typed there. That should do it. Cheers!

**Comment by QuantumGTV** [comment]
I know get: General, Web document, security and Details when I open properties. :S I have the game in steam, could that be why the tab you're talking about doesn't appear?

**Comment by karasuhebi** [comment]
@QuantumGTV You just might not be right-clicking on a shortcut. You might be right-clicking on the actual .exe file. It doesn't matter though, since you have the game on Steam you can add the -win parameter there. Right-click on the game on Steam and go Properties. Then click on "Set Launch Options" and type in -win there. That should get you going.

**Comment by QuantumGTV** [comment]
thank you @karasuhebi ! its in window mode now :D

**Comment by karasuhebi** [comment]
No problem man. Game on! :)
