### ISSUE TITLE
error for fullscreen

### ISSUE THREAD

**Issue by freezxx** [Codeusa/Borderless-Gaming#153]
I tried Star Citizen but it came up as an error the reason why I'm testing out the game I found something interesting with this program you can have a 4K desktop resolution and Run the game that a lower resolution in Windowed mode and then use the program to put it in full screen and the performance is good, because It's still in  lower resolution if you want to test out yourself this look at the FPS

**Comment by psouza4** [comment]
Sorry, but Star Citizen is known to be incompatible because it uses the Unreal Engine v3.  This engine forcibly and persistently resets window properties on windows from games using this engine.

Here is a list of other Unreal Engine v3 games:

https://en.wikipedia.org/wiki/List_of_Unreal_Engine_games#Unreal_Engine_3
