### ISSUE TITLE
Hard Reset (ingame glitch)

### ISSUE THREAD

**Issue by DCFTW** [Codeusa/Borderless-Gaming#230]
Hi all, the only way I could fix the microstuttering in this game was when I ran it 
windowed mode, so I bought BG. At first sight worked flawlessly but then when
I shoot in game there's like a weird graphical glitch. I googled the problem but found nothing
related. 
PS: This only happens when I use BG.
If anyone could help out a brother, thanks in advance!

**Comment by hauzer** [comment]
BG? Baldur's Gate? I don't think there's shooting in that one. How about a screenshot?

**Comment by DCFTW** [comment]
Nooo, lol The game I am playing is called Hard Reset! and BG is for Borderless Gaming.
Screenshots? How About a few, so there's a better chance for you to know what I am talking about.
Firstly, Shooting with bordered window:
![bordered window](https://cloud.githubusercontent.com/assets/16909978/12612895/251bcc50-c4dd-11e5-8f79-1185a1c473db.jpg)
Shooting on BG Window:
![bordered window 3](https://cloud.githubusercontent.com/assets/16909978/12612909/40ae6068-c4dd-11e5-9f37-35d508ad1993.jpg)
Menu on BG window, you can see a piece of my HUD showing where it's not supposed to.
![menu with bg](https://cloud.githubusercontent.com/assets/16909978/12612958/83b99d14-c4dd-11e5-9a7c-7562492c4270.jpg)

**Comment by Acecool** [comment]
It doesn't look like that game supports dynamic resizing ( it may be coded in such a way that it only draws changes to screen while keeping old visuals persistent )... Try minimizing and bringing it back up. That usually forces windows to redraw.

It may be a temporary fix until the other issue is resolved.

**Comment by DCFTW** [comment]
Just tried pressing Windows+D minimizing it to desktop and back to the game and still same thing.
The interesting part is that it ONLY happens if I use BG, it works just fine if I uncheck the full screen option in game, but then I wish I could play without that edge on the top of the screen. Anyways thanks for theying to help.

**Comment by Acecool** [comment]
There is something else you can try... Some games calculate size differently, but quite a few use the render-portion of the window as the size when you set it... So if you had a program to move the window off-screen a bit then you would be without the border...

Here are a few programs I use; it is outdated but I'll update it soon... The program you'll want to look at is AutoResizer. It'll let you move windows where you want them when they're detected, and it will let you resize them, among other features. It actually saves the settings too... I use it for most of my windows, and I use ALT+~ to force re-detect, so I can have a game platform I use for developing open on my left monitor along with the server window, and my coding program on the center monitor along with folder browser ( QTTabBar although with the bugs it has I may opt for something like Explorer++ [ if explorer++ wouldn't crash every 10 seconds, wasn't full of bugs regarding bookmarks and other things, and had a few more features, I'd use it ]; in short it is a must have program because Windows has no Window management built in, unfortunately. )
https://dl.dropboxusercontent.com/u/26074909/tutoring/___welcome_docs/_welcome_useful_programs_and_notepadpp_upgrades.lua.html
