### ISSUE TITLE
KOTOR2 Steam edition Autodetect repeats itself

### ISSUE THREAD

**Issue by Chastity23** [Codeusa/Borderless-Gaming#274]
Setting up KOTOR2 as a favorite causes BG to reapply the Borderless Window mode every second.  Does not do this when enabled manually.

Using 8.4.33315.1328 On Win10 Pro 1607  default settings

**Comment by Keith94** [comment]
Did you try disabling Auto-Maximize for the game, does it make a difference?

**Comment by Acecool** [comment]
This happens on several games I own; at one point ( This is in Windows 10 x64 Pro ) BG locked up and wouldn't load properly when I tried reloading it despite ending the task multiple times in task manager...

I haven't been able to replicate it which is why I didn't report it, but it did happen shortly after one of the games was loaded where BG continuously repeated applying settings to the game ( I haven't played them since because I rarely have time to play anything because of injuries sustained during a 2011 MVA where someone ran a stop sign and hit me ) - When I reloaded BG it was with the game open which is when the app locked up and wouldn't do anything... When I closed the game BG worked fine the next time I launched it..

I'm guessing it is getting stuck in some try / catch recursive operation but I have yet to review the code ( I have been meaning to add a few useful features such as mouse-click offset for games that don't scale properly by design ie where the game only updates the variables containing size from the menu instead of using specific events which occur when a window is resized leading to the clicks being off by x and y distance; adding support for games that have a blank window title [ currently they do not show up at all in the list ] and a few other things )

**Comment by Keith94** [comment]
>I have been meaning to add a few useful features such as mouse-click offset

That would be awesome if you find the time to add these. :)

**Comment by Chastity23** [comment]
Let me clarify.  When I use Auto-detect, it applies in an endless loop.  When I do not, and maximize manually, it's OK.

**Comment by niiise** [comment]
i have the same issue now trying to play kotor2 today
