### ISSUE TITLE
[Bug] Mouse is suddenly off after updating to v. 9

### ISSUE THREAD

**Issue by Auramin** [Codeusa/Borderless-Gaming#294]
I've been using BG on NWN1 for quite some time in a borderless window mode. After the update, my mouse is suddenly off compared to the buttons in the game. It's as if the game is actually not at the same spot at my cursor, which makes clicking buttons incredibly difficult. Anyway to fix this somehow?

**Comment by niiise** [comment]
have a similar problem on kotor2 , in the menus the game window seems to be aligned correctly but the cursor is vertically misaligned pretty terribly, once i start the game, the game window shifts down so that i cant see a lot of the bottom portion of the screen, but the cursor realigns to where it should. ive tried specifying window size and such
