### ISSUE TITLE
Constant CPU spikes

### ISSUE THREAD

**Issue by slikts** [Codeusa/Borderless-Gaming#302]
Win 10 CU, i5 2500K @ 4.5, Borderless Gaming 9.1

Same issue as #148 and #51. The "Use Slower Window Detection" option doesn't seem to have any effect; if I have Borderless Gaming running, it constantly spikes CPU usage to about 9%. Software that's meant to be running in the background, isn't doing anything particularly complex and isn't needed most of the time should not be using as much CPU time.

![screenshot](http://image.prntscr.com/image/fa91d827f5024938822a1dc9ea8e2ea0.png)

**Comment by CeruleanSky** [comment]
I built a release based on my personal fork: https://github.com/CeruleanSky/Borderless-Gaming/releases/tag/9.4expermiental

I've been just applying a small change for a year or two that lowers it polling to 20 seconds from 3 seconds, and lowers its process priority, since I like to leave it running in the background.

While it will always have some usage, since it needs to scan for games, why don't you see if that helps your situation, at least a little bit.

**Comment by Codeusa** [comment]
I will be replacing this code in the next week, it is really janky and doesn't really follow what I consider to be asynchronous program design. As a result you should see lower CPU.

**Comment by mickdekkers** [comment]
I'm having the same issue, where it constantly spikes to 10-15%. In my case, the spikes appear to last longer though (either that or the graph in the OP is over a longer timespan). For reference, they seem to last about 20 seconds per spike.

![](https://puu.sh/yPFtL/5633ed8209.png)

Win 10 Pro, i7 3770k @ 4.5GHz, Borderless Gaming 9.4.9.1328

**Comment by Ryonez** [comment]
I've noticed this recently myself, with I/O spikes as well:
![image](https://user-images.githubusercontent.com/16157130/42721554-c5746b58-8790-11e8-9bfa-af2dee4cf3b5.png)

**Comment by Ryonez** [comment]
I tried switching to slower window detection and it resulted in this:
![image](https://user-images.githubusercontent.com/16157130/42721571-1423e922-8791-11e8-91a0-630a84aab8c6.png)
