### ISSUE TITLE
Rights granted by the GPL cannot be retroactively retracted

### ISSUE THREAD

**Issue by omcnoe** [Codeusa/Borderless-Gaming#312]
The GPL grants the public the right to code licensed under it, as long as changes are publicly available. You cannot retract this right for existing GPL licensed versions.

Issuing DMCA takedowns of code licensed under the GPL is illegal, and I'm sure will be looked down on strongly by the community. You really shouldn't try.

**Comment by Codeusa** [comment]
I can understand your concern, most of the noise being made is because I announced I'd stop offering free releases while keeping the source code open. 

I tried to handle this gracefully at first, making the discussions public and purposefully shining a light on them. I didn't at any time try to hide my changes. As the conversations devolved into ad hominem and "gotcha" moments of my character, I just decided to exit stage left. 

So here is what I'll do to resolve this:

- I'll agree to restore the GPL status of the current code base, transferring my MPL commits over to GPL. 
- The entirety of the software will be rewritten under MPL.
- Future contributors will be asked to sign an agreement
-  Compiled releases will still not return
- I'll be transparent about any future changes well in advance.

So why did I switch to MPL? Trademarks and branding mostly, I don't want derivative works to use the Borderless Gaming brand if it isn't for personal use. The repository that was DMCA'd specifically did this while also removing all references to the original fork which I think you can agree also goes against the GPL.

**Comment by cheatfreak47** [comment]
While that solution is considerably better @Codeusa it still doesn't make you look very good.

The only problem I have with this change overall is that you built a name for this software on it being a free and open source program, and now you backpedal and decide to go to try and sell it instead, and change the license so that any free versions have to change the name.

And make no mistake- this change makes Borderless Gaming a commercial product instead of a freeware program, since you are using a license to restrict distribution of unofficial builds using the same name.

Do you think Borderless Gaming would be where it is now if you had been only selling it for $3.99 to begin with? If not, is it morally right to start selling this software now after it's built it's reputation for being free, open source, GPL software?

Do you know how many guides and wiki pages out there list this free and open source software as the best solution for running games in borderless windowed fullscreen that will be propagating a lie outright now because of your changes here?

This is a decision entirely motivated by greed, and for that you've lost my respect.

"Borderless Gaming is staying free, don't worry."
Yeah right. 

Have fun with your money, you won't be getting any of mine.

**Comment by witheld9** [comment]
And all of the illegal, under penalty of perjury DMCA notices you sent?

**Comment by Codeusa** [comment]
@cheatfreak47 The software is still free and it is still open source. Saying I'm backpedaling seems disingenuous, I've offered free binaries for close to 5 years now. I have no plans to close this repo even after the rewrite and I have no plans to stop pushing new code. So in every sense of the term, this project is free and open. 

Speculation as to why I've decided to host changes exclusively on Steam is just that. I refuse to dive into the details of my personal life and what circumstances forced my hand. I've done my best to accommodate people. The Steam version is DRM free, can be copied to other devices and even works off a USB.

I'm going to continue creating software the community finds useful.

**Comment by cheatfreak47** [comment]
@Codeusa You are gating freely avaliable and easy to obtain compiled binaries of the latest version of the software behind a paywall to incentivise people lining your pockets, and actively making changes to the license to discourage forks that compile and distribute binaries.

On top of that, right after the license change you sent a DMCA takedown on one of the forks of this project already.

The average user isn't going to know how to compile the software from source, and to get the latest DRM Free officially released binary from the steam version requires someone to pay you the 3.99$ in the first place- and I'm sure you wouldn't be too happy if people started posting those publically.

It is not going to be free anymore after this in the absolutely most important sense: that after this, people will have to buy a copy of the software through steam get an easy to install, recent build of the program without having to go to the trouble of compiling it.

And no, it's not disingenuous to say that precisely because you offered free binaries for 5 years and now you've decided specially _not_ to do that, and to make it more difficult for free binaries to be produced by third parties.

That, in my book, is the definition of backpedaling.
Not only that but you backpedaled after you benefited from where your bike went.

Anyhow, I didn't come here to argue with you, I'm just telling you what this looks like to me, an average guy who used borderless gaming for _years._

**Comment by Codeusa** [comment]
@cheatfreak47 

>DMCA takedown on one of the forks of this project 

That was in clear violation of the GPL and close to infringing. The fork not only removed every reference of me from the repository, it removed my copyrighted headers from my code.  This crosses the line and it was clearly done out of spitefulness. This project has been forked and mirrored hundreds of times and that is hopefully the only time I'll ever have to do that.

>The average user isn't going to know how to compile the software 

Then I ask the average user to pay a small premium for a utility they will likely use daily, or find a mirrored source elsewhere. I'm pretty sure Sourceforge has every version. I honestly wouldn't care if each new version was released outside of Steam by someone else. By all means, "pirate" the software.

**Comment by omcnoe** [comment]
> The entirety of the software will be rewritten under MPL.

There is no need for this, as the copyright holder you can license the whole project under MPL as long as you get agreement from all other contributors, or replace code written by contributors who do not agree.

What you CANNOT do is retroactively retract rights granted under the GPL, such as that now removed requirement that forks do not provide compiled binaries. As commits done before a valid license change to the MPL will still be under the GPL.

**Comment by omcnoe** [comment]
As you have removed LICENSE2.MD, this project is no longer violating the GPL. Sorry if I wasn't able to make that clear with my first comment, but LICENSE2.MD was the explicit GPL violation.

**Comment by cheatfreak47** [comment]
@Codeusa if that's what he actually did, then that's fair enough.

> *ask* the average user to pay a small premium for a utility they will likely use daily

And it's fine to ask, but the difference is, now people _have to_ pay for these safe, legit, and official builds. Before, they did not. This makes Borderless Gaming a premium software now. Borderless Gaming made a name for itself as a free software with optional, non-intrusive ways to donate to you by paying for the steam build.

There are a lot of people that probably only bought the software to support you _because_ this software is free, open, and accessible, and it's such a useful program that a lot of people use daily.

By making that the _only_ method for official delivery, you are effectively making Borderless Gaming a commercial product, and that is a decision I just cannot agree with, because of the precedent that it had set as being a piece of freeware.

If you want to look at how to do steam released free/open software right, have a look at how ShareX does it.

**Comment by Codeusa** [comment]
@omcnoe I understand and in hindsight it was a pretty stupid decision. So I apologize, it was honestly a knee jerk reaction. 

@cheatfreak47 I am disappointed that this change has turned you off from the software, but I can understand you have your principles and ideals and I respect that. I'm committed to keeping this software open regardless and I still want to create free tools for the community.

**Comment by cheatfreak47** [comment]
@Codeusa It's fine really, we all have knee-jerk reactions sometimes.

And sorry if some of the things came off as mean spirited, I was just a little boggled at your decisions here, I still am honestly. I'll probably end up buying it anyway at some point during a sale because I use it so often. 

¯\\_\(ツ)_/¯

**Comment by SubstituteCS** [comment]
@witheld9 he did file a DMCA under perjury and I am now looking towards legal council.

**Comment by SubstituteCS** [comment]
I should also add, I never changed a **_SINGLE_** line of code.  The only thing(s) I removed were links to his personal social media accounts (the support links) and the links to Steam.  
**This is entirely allowed under the GPL.**

**Comment by Codeusa** [comment]
@SubstituteCS You violated the GPL by removing links to the original source and scrubbing references to myself out of the program. 

Due to the fact you've mentioned you're "looking towards legal council." I'm going to ask that you stop commenting on this issue until your council reaches out to me at which time I will provide him with my councils contact information.

**Comment by SubstituteCS** [comment]
No I didn't, GitHub always maintains a back-link to the original branch.  
My counter-claim has been filed.

**Comment by Codeusa** [comment]
@SubstituteCS as I stated before please don't comment on this issue until your council has reached out. I cannot in good faith engage in a discourse while you're actively planning legal action. If you wish to become a witness against yourself, do it elsewhere.

**Comment by Codeusa** [comment]
For transparencies sake, I've reached out to every major contributor and asked them to grant me permission to re-license the software and transfer their copyright to me.

**Comment by SubstituteCS** [comment]
Retract your illegally filed DMCA.

**Comment by ExtReMLapin** [comment]
つ ◕_◕ ༽つ OR RIOT つ ◕_◕ ༽つ

**Comment by purpleidea** [comment]
@Codeusa 

>  I don't want derivative works to use the Borderless Gaming brand if it isn't for personal use.

I think you're confusing copyright law and trademark law. Go and get a registered trademark for your "brand" and keep the code base GPL2+.

**Comment by Codeusa** [comment]
@purpleidea GPLv2 does not expressly describes the allowance of using contributors' names, trademarks or logos, which is the issue. When this license was chosen I was never under the impression the project would become so popular. There are other issues with GPLv2 that switching to MPLv2 will address. 

MPLv2 better fits the future I see for this software.

**Comment by pm79080** [comment]
_Commercial_ is not an antonym for Free Software.

gnu.org/philosophy/selling.en.html

**Comment by pm79080** [comment]
@cheatfreak47 [_Commercial_ is not the antonym of Free Software.](gnu.org/philosophy/selling.en.html
)

Nevertheless, distribution through steam will enslave users.

**Comment by pm79080** [comment]
@cheatfreak47 [_Commercial_ is not the antonym of Free Software.](gnu.org/philosophy/selling.en.html
)

Nevertheless, distribution through Steam will enslave users.

**Comment by Aidoboy** [comment]
@codeusa Just make sure you tread incredibly lightly. I'd like to point to the past example of Bukkit, a system for adding plugins to Minecraft server. The whole of it is still locked under a DMCA request because a single contributer didn't agree with it being bought by Mojang when the project was going under. GPL is powerful beast.

**Comment by pm79080** [comment]
@cheatfreak47 [_Commercial_ is not the antonym of Free Software.](https://www.gnu.org/philosophy/selling.en.html)

Nevertheless, distribution through Steam will enslave users.

**Comment by Codeusa** [comment]
As yet another update, I've decided to adjust how releases will work. Rather than providing no compiled releases at all, I will do trailing releases were new major updates are pushed to Steam first and later at a fixed duration Github.

the 9.3 installers are up  https://github.com/Codeusa/Borderless-Gaming/releases

**Comment by cheatfreak47** [comment]
@pm79080 nice quadruple post.
Commercial in terms of economics, refers to the express intent to make a profit, and not necessarily to benefit the public. 

It's

**Comment by Dankman** [comment]
http://www.groklaw.net/article.php?story=2006062204552163

> "If` you change your mind and don't want to use the GPL any more, you can stop and use something else **on new code going forward**, and you can dual license your own code, but **you can't redo the past and pull back GPL'd code.** That's one of the beauties of the GPL, actually, that even if some individual gets a bug up his nose, or dies and his copyright is inherited by his wife who doesn't care about the GPL and wants to take it proprietary, or just to imagine for a moment, a Megacorp were to buy off a GPL programmer and get him to pretend to revoke the GPL with threats, and even if it were to initiate a SCO-like bogo-lawsuit (based perhaps on a theory under Copyright Law § 203, termination of rights -- lordy do we have to endure a living demo in some courtroom somewhere of every antiGPL theory found on every message board before they give up?), it doesn't matter ultimately, I don't think, as to what you can and can't do with the GPL. The GPL is what it is. Please don't use it if you don't like the terms."


the linked article has more info on this topic. Essentially, if you want to change the license, you can't revoke the rights of people who already forked it under GPL. You can change your license going forward, but that doesn't change the rights you granted in the past.

Additionally

http://gplv3.fsf.org/wiki/index.php/Compatible_licenses

might be of use to you

**Comment by Dankman** [comment]
https://www.mozilla.org/en-US/MPL/2.0/FAQ/

Q14: May I combine MPL-licensed code and (L)GPL-licensed code in the same executable program?

Yes, by creating a "Larger Work" under the terms of Section 3.3. In particular, three requirements must be met:

The software must not be “Incompatible With Secondary Licenses.” Software can become “Incompatible With Secondary Licenses” in one of two ways: the original author marks it as such by adding the file header in Exhibit B, or the original author published the software under MPL 1.1 and did not dual- or tri-license the code with the (L)GPL.

The Larger Work must be "a combination of Covered Software with a work governed by one or more Secondary Licenses." So you can't just say "I really prefer (L)GPL" - you must have a need to combine with another, existing GPL work. (This is different from a traditional dual-license, which does not require you to combine, and instead allows you to simply say "I've decided to be GPL-only.")

You must "additionally distribute" under (L)GPL. In other words, you must make the MPL-licensed source code available to your recipients under both MPL and (L)GPL. Someone downstream from your recipients can then take under (L)GPL-only or MPL-only. This is different from a traditional dual-license, which never requires publication under both licenses, and so always gives you the option of releasing incompatibly-licensed code.

No GPL-compatible license can perfectly preserve the original author's ability to reuse downstream derivatives, but the last two restrictions serve to increase the probability that such reuse can occur in the broadest possible set of circumstances.

We have written a [document](https://www.mozilla.org/en-US/MPL/2.0/combining-mpl-and-gpl/)  explaining how to do this in practical terms, i.e. what to do about license headers and so on.
