### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by Svetomech** [Codeusa/Borderless-Gaming#324]
I can't compile the project anymore.

![image](https://user-images.githubusercontent.com/7114815/27495785-0467c1da-585c-11e7-9765-7d8f5fcdfb6d.png)

**Comment by Codeusa** [comment]
Remove the strong name key or create your own.

**Comment by DominykasPetke** [comment]
And for me it is this: 

NuGet Package restore failed for project BorderlessGaming_Standalone_AdminUAC: Unable to find version '2.5.27' of package 'TaskScheduler'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'TaskScheduler.2.5.27' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'TaskScheduler.2.5.27' is not found on source 'https://api.nuget.org/v3/index.json'.


As far as I can see [here](https://www.nuget.org/packages/TaskScheduler/) the version 2.5.27 is deleted. Any help with that?

**Comment by Codeusa** [comment]
Seems maybe the package was removed after I added it, I will downgrade it.

**Comment by luop90** [comment]
Just CTRL+F through the install .iss configuration files, and remove any reference to signing the .exe (It's ~3 properties in each file)

**Comment by BonnyDev** [comment]
To get it to compile (worked for me but please read to end, I´m guessing from Codeusa´s response this will be fixed in src soon)
1. Open the solutions properties and de-select **Sign the assembly** (I´m guessing this is for source validation? Since the keyfile isn´t from me and I wont re-distribute i have nothing checked)
2. Open the **packages.config** file in the solution and remove the line `<package id="TaskScheduler" version="2.5.27" targetFramework="net45" />` then save the file.
3. Right click the solution again and select **Manage NuGet Packages**, the **Installed** tab should only contain **Newtonsoft.Json**, you can now enter the **Browse** tab and search for "TaskScheduler" and install the one from David Hall v2.5.23 and allow visual studio to update the project.
4. Try to compile.

I am NOT an avid programmer and do not know if any of these steps are wrong or if they in any way might damage the project and cannot take responsibility for any mishaps, it is simply what I did to get it to compile.

Cheers

**Comment by wtchappell** [comment]
You no longer need to downgrade the TaskScheduler version - it builds fine with the version currently listed.

You do, however, need to copy the Languages.zip file into the same directory as the program.

Also, for those who want an installer as well, you can build those and use them if you also install Inno Setup and add it's directory to your Windows PATH.
