### ISSUE TITLE
Open very slowly, before the update or soon open! There are DPI problems

### ISSUE THREAD

**Issue by dsyo2008** [Codeusa/Borderless-Gaming#326]
Open very slowly, almost more than 20 seconds after the show, why more than the version of the regression?
How does DPI fail? Easy to use before updating, DPI normal.
From steam, a little disappointed, feeling more and more backward, or a problem. As the previous version

**Comment by Codeusa** [comment]
I'll push a fix for DPI now, I just left out a config.

The entire software is being rewritten, under the hood everything needs to change. I'm going to need more information for "opening slowly" because you're not really telling me anything. The application opens instantly for myself. I need a means to reproduce.

**Comment by dsyo2008** [comment]
Thank you, the original is rewritten, I'm sorry, I am sorry!
And so on to look forward to perfection!
