### ISSUE TITLE
Unhandled Exception in version 9.4.9

### ISSUE THREAD

**Issue by jarquafelmu** [Codeusa/Borderless-Gaming#330]
Running version 9.4.9 of borderless gaming in administration mode, there was an unhandled exception that caused the program to crash when I started up my computer. I tried to find logs to help point out the issue but I haven't been able to locate any. If the issue happens again I'll try to screen capture it.

I know this report isn't all that useful as it doesn't really give a whole lot of instruction on how to reproduce but I figured knowing that there is an unhandled exception might be helpful, at least so it's on your radar.

thanks again for your awsome tool.

----

**Borderless Gaming**: 9.4.9 (administration)
**Windows**: Windows 10 Pro 1703 build: 15063.413
**Steam**: API: v017, package version: 1496897923

**Comment by jarquafelmu** [comment]
I said I would update when I found the logs.

[UnhandledException_7-3-2017.txt](https://github.com/Codeusa/Borderless-Gaming/files/1120235/UnhandledException_7-3-2017.txt)
[UnhandledException_6-30-2017.txt](https://github.com/Codeusa/Borderless-Gaming/files/1120237/UnhandledException_6-30-2017.txt)

**Comment by JoeCrescoll** [comment]
Apparently commit 0fbafabc89dde0c13e8b74af1543c58bc48da6f4 fixes the exception, but now the program just reports that the UI translations are missing and then quits.
I had to manually copy the _Languages_ folder (found at the root of the project) to "_%USERPROFILE%\AppData\Roaming\Andrew Sampson\Borderless Gaming_" in order to use the program.
