### ISSUE TITLE
dongeon siege 2

### ISSUE THREAD

**Issue by johanais** [Codeusa/Borderless-Gaming#436]
hi,could you take a look at this game under win10,used to work fine until win7 but with win 10 only works in windowed mode,i tried your software and the game does start in full screen but the welcome menu is in quarter of the screen and when the game starts the resolution is really uggly and the mouse doesn't click well on selecting wich weapon to use for exemple or if press escape for menu can't click.....i really love comming back to this game once in a while so if you could fix that would be great!!

**Comment by Chaython** [comment]
This software is no longer supported, last update was a version bump to kill the nagging

**Comment by Ds886** [comment]
It happens because the menu resolution is unchangeable(800x600) and the game calculate the buttons based on the initial resolution so when fitted to your monitor resolution the game doesn't update the button placement values while the screen does.(It was probably done because  800x600 was the most hardware agnostic resolution at the time  as 640x480 14" CRT phased out by 2006 and they wanted to give a safe place to change resolution without an external launcher or manually editing the config files in notepad.)

disable resize(no size change in the right click) and it wouldn't fill your screen  but it should be fixed in terms of mouse placement and will make the menus usable

**Comment by johanais** [comment]
i don't know if it's the update you did on your software but now works great except for the quarter screen when first menu....the perfect combo is to add  fullscreen=false width=1024 height=768 to the shortcut of the game,and in your software no other options then full screen!!! so thanks having fun since it now works!! if this thread helps anyone i am not using steam to launch...
