### ISSUE TITLE
Does not work with minecraft windows 10 edition

### ISSUE THREAD

**Issue by Caio-Sc** [Codeusa/Borderless-Gaming#454]

**Comment by Chaython** [comment]
Minecraft windows 10 edition is borderless window [all UWP games]

**Comment by Ryonez** [comment]
> 
> 
> Minecraft windows 10 edition is borderless window [all UWP games]

Simply not true. If you alt-tab the window minimizes. So not true borderless window.

**Comment by Chaython** [comment]
It's an efficiency thing, UWP games are meant to pause in the background.
"Other games pause on foccus loss" 
UWP doesn't just pause, it flushes some assets. Because all applications run in the background by default. UWP is meant to be scalable, to tablets, they can afford minimized apps freezing up the system/killing the battery.

**Comment by Ryonez** [comment]
> If you run a game in a window it will continue to run / will not pause on focus loss.

And then you run the borderless window app on it, and get true fullscreen borderless.

If Microsoft is claiming that what they are doing is fullscreen borderless, I'd disagree with them due to it behaving in a non standard behavior.

**Comment by Chaython** [comment]
If you use borderless gaming it will stretch the window to the full screen resolution ; but the border will still appear and the application will run below the taskbar

**Comment by Ryonez** [comment]
> but the border will still appear

I haven't seen that issue.

> the application will run below the taskbar

I've seen this with some programs, pinning/unpinning the window to the taskbar seems to fix  it.

**Comment by Chaython** [comment]
If you push the windows key rather than alt tabbing; you can use your second monitor without the application minimizing
It sounds like you haven't used UWP?

**Comment by Chaython** [comment]
If you want to alt tab without the game minimizing [pretty redundant as you have an app ontop and maximizing returns to the same state [aside from halowars where matchmaking cancels upon alt tabbing]
You can switch between windowed and borderless by win shift enter
So just switch to windowed before clicking another app

**Comment by Ryonez** [comment]
> It sounds like you haven't used UWP?

I have, but not often at all. Aside from the built in windows app, I've only really played a few uwp games. So I'll defiantly be missing things like that. Especially with the strong habit of alt-tabbing.

**Comment by Chaython** [comment]
Well alt tabbing minimizes it, it reopens within <50ms unpercievable, turn off windows animations it will pop in a single frame.
If you're doing something that requires you to not minimize the game such as matchmaking in halo wars, then you must push win shift enter to go to window, when you want borderless again push win shift enter again.

**Comment by Chaython** [comment]
It's been awhile since I played HW I forget what exactly the issue was with minimizing and matchmaking; maybe once in match it kicks you if it was minimized...
Anyways minimizing maximizing is instant, the resizing from windowed to borderless has a little delay, because the internal rendering resolution is changed, but that's just the resizing, if you were faster than the <180ms to resize you could still click stuff in the game.

**Comment by xmas-dev** [comment]
> And then you run the borderless window app on it, and get true fullscreen borderless.

This is not true for UWP. Running borderless on Minecraft for Win 10 does not hide the borders in windowed mode :/
