### ISSUE TITLE
Stop steam from closing this

### ISSUE THREAD

**Issue by willho01** [Codeusa/Borderless-Gaming#514]
I have GOG setup to close steam when I exit a steam game. The problem is, steam ALSO closes borderless gaming. Can this be stopped. I want to use borderless gaming outside of steam. The fact that valve seem to think not wanting their bloatware running in the background at all times is some sort of crime that means I cant use BG is just absurd.

**Comment by Acecool** [comment]
The Borderless Gaming people can remove the Steam API from the software so
that Steam doesn't detect it if it is run from the exe, then just have it
run automatically.
If it is already like this, then just have it open automatically.
Otherwise, ask them to remove the api, as it isn't necessary for free
software anyway and adding 'playtime' doesn't make any sense especially
when insurance agencies will use that against you in court, even if free
software is emulating it.


-Josh 'Acecool' Moser
Acecool Company
Hendersonville, N.C. or Charleston, S.C.
Tel.: +1.843.580.2134

This message contains confidential information and is intended only
for the individual named. If you are not the named addressee you
should not disseminate, distribute, or copy this e-mail. Please notify
the sender immediately by e-mail if you have received this e-mail by
mistake and delete this e-mail from your system. E-mail transmission
cannot be guaranteed to be secure or error-free as information could
be intercepted, corrupted, lost, destroyed, arrive late or incomplete,
or contain viruses. Therefore, the sender does not accept liability
for any errors or omissions in the contents of this message, which may
arise as a result of e-mail transmission.

Acecool is a Legal Trademark since 1989 through 2019 and beyond according
to TradeMark LAW which closely mimics copyright law. When a new and unique
name / creation is made, that creation is automatically TradeMarked or
Copyright Protected under the law. I am the original creator of the Acecool
brand in 1989 which creates a unique spelling for 'A School' which follows
my philosophy in life, therefore I am also the TradeMark holder. Legally,
TradeMarks and Copyrights do not need to be registered with the TradeMark
or Copyright office as the protection under the law is automatic.

I have been using the brand / company name Acecool since 1989 through the
current-date for all of my businesses under the umbrella of Acecool, and I
use it as my legal identifier online for my Businesses.
