### ISSUE TITLE
Genshin causing crash

### ISSUE THREAD

**Issue by ArcnetZero** [Codeusa/Borderless-Gaming#524]
I am not sure what exactly causes it but the application frequently crashes when trying to work on this application. And when it does succeed it sometimes creates two windows for it. One completely blank page, and then the real one

**Comment by izzy** [comment]
I can confirm that Genshin really doesn't play nicely with BG. At the moment it behaves in such a way that auto maximize doesn't work at all and I have to do a full app refresh or restart BG before I can maximize the Genshin window manually.

When I try to restore Genshin to its bordered state, BG locks up completely. 

The blank one is probably an artifact leftover from the launcher.

**Comment by Rafii2198** [comment]
I actually use BG with Genshin. The problem is that when you add it to favorite, it will automatically work on the launcher too. And that can cause problems as it is not prepared to be resized. What happens for my mostly is that when I close the borderless launcher it comes back after few seconds (as it is just going to the tray) but completely transparent, this also rarely happens when I launch the game.
I found a bit of workaround and not proper fix but it allows me to play normally:
1. If you have multiple monitors, you can see 2 different Genshins on taskbar on different monitor. If you right click on them you'll see either `genshinimpact.exe` or `launcher`, you want to close the launcher.
2. If you don't have multiple monitors you can alt+tab to other window, and follow previous steps. Make sure to alt+tab to a window that is not Genshin or Launcher.

I think there is no way to fix it as from what I have seen, they are both share the same process.

**Comment by farsdewibs0n** [comment]
> 

Same issue occurs too on Honkai Impact 3

**Comment by Rafii2198** [comment]
Found answer. It is similar approach like with Terraria or other games. To fix this you need remove Genshin from your favorite games, then launched it, and then add it to your favorites by the process binary name.
You do this by right click on Genshin Impact on the left panel (Make it says just `Genshin Impact` not `Genshin Impact [Launcher]` as this is the launcher not the game), and from Add to Favorites... option pick `... by the process binary name`.
![genshinbg](https://user-images.githubusercontent.com/26695327/179972422-a2f9f9fc-78a0-4b96-91b3-89529bd80e95.png)

This will make Borderless Gaming work only for the game itself and not the Launcher.



>Same issue occurs too on Honkai Impact 3

This should work exactly same for Honkai, but of course you would have to add Honkai not Genshin for it to work. Unless there is something I don't know about, I never played Honkai on PC.

**Comment by farsdewibs0n** [comment]
> 

This issue also happens on honkai, im sure thats the issue
