### ISSUE TITLE
Unknown error (0x8) Win32Exception at System.Diagnostics.NtProcessManager.GetProcessIds

### ISSUE THREAD

**Issue by dspearing** [Codeusa/Borderless-Gaming#550]
Happens randomly when not even using the application other than it being in the system tray.

[UnhandledException_12-22-2021.txt](https://github.com/Codeusa/Borderless-Gaming/files/7764469/UnhandledException_12-22-2021.txt)

**Comment by oold** [comment]
From a quick glance at the code, this is probably caused by a process exiting after the window handle was enumerated. There is some delay between the window handle list being populated and the process ID being queried. To be honest, it's not even safe to say that the window handle isn't reused by another process at that point, but what can you do.
