### ISSUE TITLE
[vNext] Wishlist

### ISSUE THREAD

**Issue by andrewmd5** [Codeusa/Borderless-Gaming#593]
Hi folks,

After a long hiatus I’m actively working on the next major update for Borderless Gaming; a more detailed thread of features will follow but until then I want to ask - what are the features/fixes you’d love to see in the next update?

**Comment by M0nsh3r1** [comment]
I originally downloaded the application to remove the window frames. But I removed it due to the fact that it not only removes the frames but also makes the game fullscreen. And I don't need fullscreen. Because I need a game in the window, but without window borders, which the name implies. I hope this helps)

**Comment by VitaMoonshadow** [comment]
Hello, thank you for opening this up. I would love it if there was an option to set a hotkey that would toggle the borderless fullscreen state of a window on or off. Win + F6 as a global hotkey doesn't seem to work for me at all, and I really just want to toggle things with one button just like you do for normal fullscreen with F11.

**Comment by bernhardkelm** [comment]
Hey, first of all thank you for continuing the development, this is great to hear!
A few things I would love to be added:
- I would love to be able to edit Zones for windows not just by Dragging the window while creating the zone but to add numeric values. Currently, due to only being able to drag it's not very precise.
- The ability, to save these Zones as Presets and apply them to my favourites. For example, I am using a 42" Monitor and for certain Applications I want a Zone which fills the entire width, but not the entire height of the screen, for others I want a 16:9 image which has a smaller resolution but is centred to the bottom. Being able to create presets for this would be very welcome.
- Lastly, it would be awesome if we would be able to choose one of the presets when adding an application to our favourites via the Right-Click context menu. Currently, if I want to add an application for a certain size I have to add it to my favourites (where it defaults to "Max size") and then change the window positions and sizing afterwards.

**Comment by daviddob** [comment]
Hi @AndrewMD5, thanks for the awesome work, really helps play some old titles on new hardware!

I would love to see:
- Automatic Cursor Locking on focused window implemented, would be a huge QoL improvement (#137)
- Possibly the ability to set a full screen resolution instead of stretching (centered, optional black bars on side)

---------------

Also @M0nsh3r1 I think what you want already exists, if you add the app to favourites, then right-click and select "No Size Change" it doesn't stretch to fullscreen anymore and stays fully windowed.

**Comment by Aezriel82** [comment]
> 
> * Possibly the ability to set a full screen resolution instead of stretching (centered, optional black bars on side)
> 
THIS PLEASE :P - so many games' fullscreen  windows ' options DONT offer aspect ratio changes... this would almost GLOBALLY fix this for so many ppl. --- currently i set my taskbar to autohide and desktop BG that isnt too obtrusive that i can still see instead of "black bars"... all black would be great.

possible solution:  u could probably just add an option to place a Black.img UNDERlay behind the window, set to the size of ur screen res. and just set the window position to where u want (size and scale) using the "Set Window Size" BGW option
