### ISSUE TITLE
HELP SOMEOF MY APPS ARE STUCK IN BORDERLESS

### ISSUE THREAD

**Issue by odiplol** [Codeusa/Borderless-Gaming#601]
i have installed this program, it is pretty good, i have tried it with pcsx2 and now its stuck in borderless. i have tried uninstalling and reinstalling the app and it doesnt fix it. please help

**Comment by wymzi** [comment]
I'm having the same issue.  I found this program specifically for one old game that has framerate issues in fullscreen and a tiny, non-resizing windowed mode.  As soon as I applied borderless gaming to that game, it broke.  The game's buttons were not registering in their proper locations, but were acting like they were in the places they were on the tiny window.  Telling borderless gaming to return the game to its framed window did nothing.  Uninstalling borderless gaming did nothing.  Uninstalling and reinstalling the game did nothing.  The game is now unplayable because the buttons are not properly mapped on the screen in borderless window, and has like 3 fps in fullscreen.

**Comment by Aezriel82** [comment]
have u considered;

whenever closing the BGW app it has an option to stay open to the system tray, so long as its running in system tray, the windows borderless commands will apply. only after closing the BGW from the system tray or task manager will windows return to normal state. 

uninstalling and reinstalling will still retain the user config from last install. -  i think its found in %appdata% folder.

THAT IS- if the BGW app in NOT running in the system tray/taskmanager  the window should appear normal. 

the mouse offset issue is what i believe another bug all together  - 
https://github.com/Codeusa/Borderless-Gaming/issues/606


somehow, first impression is that BGW is still running and settings are still being applied.


- first step to a solution is to cross off the obvious-

**Comment by James-Willer** [comment]
I seem to have this same issue
closing the process completely doesn't seem to fix it.
the app stays stuck on borderless mode

**Comment by Skorflex** [comment]
Have you figured out how to fix the bug?
