### ISSUE TITLE
Cursor Issue

### ISSUE THREAD

**Issue by Nhawks1717** [Codeusa/Borderless-Gaming#62]
This is probably just per game but I am using this on Civilization 5 and I have noticed that when this is applied the cursor that is provided in game by Civilization 5 is not positioned correctly to where the actual selection is taking place on the UI. Its not a bid deal since its only offset by a little but it is a big enough problem to where it is effecting clicking on certain things. Like I said this is probably just an issue with Civ 5 because of their curosr but I'm not sure. I don't really have any other games to test this on that don't already have their own version of Borderless Window.

**Comment by ZwaanME** [comment]
I have a similar problem using Borderless Gaming with games like Empress of the Deep (hidden object game) that run in a low resolution (800x600 or 1024x768). When I run games like these without a border they no longer scale the position of the mouse cursor which makes it almost impossible to play. The middle of my screen is interpreted as the lower right corner making it hard to click buttons. Is there any way to correct this? I can't change the resolution as suggested because these games only run in one resolution setting.

**Comment by psouza4** [comment]
Unfortunately, some games are incompatible as they don't check their resolution or use scaling techniques to understand screen coordinate translations.  So when the window size is changed, the mouse position offset is wrong.  There's nothing Borderless Gaming or other window-resizing applications can do to fix this, I'm afraid.  You can run it borderless without resizing the window if you just want a clean feel to the game, but it's just an oversight in how the game translates mouse inputs to on-screen game elements by not accounting for smooth resolution sizing.

**Comment by ZwaanME** [comment]
Dear Peter,

Thank you for your swift reply. I thought it would be something like 
this but I'm glad I didn't miss an obvious or advanced feature of the 
program. I have managed to get the software to work with a variety of 
games and when it works it's great to be able to do something on my 
second monitor without losing focus.

---
Kind regards,

MARK ZWAAN

Peter Souza schreef op 2015-07-25 18:22:

**Comment by psouza4** [comment]
Glad that works for you!

**Comment by tapcio** [comment]
Hello,

Sorry for writing in this old issue, but you wrong about:
> There's nothing Borderless Gaming or other window-resizing applications can do to fix this, I'm afraid. 

You can fix this by injecting custom DLL into game process and hook `CreateWindowEx` and `SetWindowLong`. This is aggressive method, but I have working d3d9.dll wrapper for Civilization 5 (also work for DX11 because executable loads d3d9.dll too) that overcomes cursor offset bug. I think something similar is doing GeDoSaTo but it have more advanced injection schema.

My code is here: http://www24.zippyshare.com/v/sW2NUY9l/file.html I need to create github project for it someday ...
