### ISSUE TITLE
Program crashes after launching

### ISSUE THREAD

**Issue by ElHyperion** [Codeusa/Borderless-Gaming#63]
As I doubleclick the BorderlessGaming executable, the thing appears in my tray, with a bubble "Borderless Gaming is minimized.". But after I hover over it, it disappears. I've checked the task manager and there's a process called "Windows Problem Reporting" popping up shortly after the program is started, and then it disappears along with the Borderless Gaming process

**Comment by psouza4** [comment]
Ben-Kaniobi: your exception is indicative of .NET framework corruption.  You may need to try the usual repair steps for .NET issues:

* running system file checker (SFC /SCANNOW) from a command prompt
* running repair installations on any .NET frameworks you've installed that aren't automatically part of the Windows operating system. For example, Windows 7 comes with .NET 2.0 already, so you can't repair install it (but you can repair install 3.5, 4.0, and 4.5).  Since you're on Windows 8.1, you may not be able to repair install many .NET packages.
* using Borderless Gaming from another user profile's desktop on the same computer (this checks a few different things about the user environment).  You can even just create a new user profile on the same PC to test with.
* trying a different system (laptop or PC) from the same network (verifies non-local .NET framework corruption status)
* verifying that WMI is working correctly using http://www.microsoft.com/en-us/download/details.aspx?id=7684 and http://technet.microsoft.com/en-us/library/ff404265.aspx (version for Windows 8 posted here https://www.dropbox.com/sh/k0g6y7occ55l1im/AACoMQvEWuoIDBssR7nrBpJUa/WMIDiag.vbs)

**Comment by cfrost** [comment]
I have pretty much the same problem, at almost same hardware and OS setup.

My logs say: 
```
Faulting application name: BorderlessGaming.exe, version: 7.9.1415.1112, time stamp: 0x54bfdc5b
Faulting module name: KERNELBASE.dll, version: 6.3.9600.17278, time stamp: 0x53eebf2e
Exception code: 0xe0434352
Fault offset: 0x000000000000606c
Faulting process ID: 0x1cc8
Faulting application start time: 0x01d035b8c5e1c791
Faulting application path: C:\Users\Frost\Downloads\BorderlessGaming.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report ID: 041e1623-a1ac-11e4-826f-448a5bcb4536
Faulting package full name: 
Faulting package-relative application ID: 
```
And a .NET error
```
Application: BorderlessGaming.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
Stack:
   at BorderlessGaming.Utilities.ExceptionHandler.<AddGlobalHandlers>b__1(System.Object, System.Threading.ThreadExceptionEventArgs)
   at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.SafeNativeMethods.ShowWindow(System.Runtime.InteropServices.HandleRef, Int32)
   at System.Windows.Forms.SafeNativeMethods.ShowWindow(System.Runtime.InteropServices.HandleRef, Int32)
   at System.Windows.Forms.Control.SetVisibleCore(Boolean)
   at System.Windows.Forms.Form.SetVisibleCore(Boolean)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at BorderlessGaming.Program.Main()
```

**Comment by Codeusa** [comment]
Try the installer that was just pushed to releases

**Comment by cfrost** [comment]
Works flawlessly ! Thanks!
