### ISSUE TITLE
Vendetta Online not working with 7.5

### ISSUE THREAD

**Issue by Patterner** [Codeusa/Borderless-Gaming#94]
I used 6.5 without problems.

**Comment by psouza4** [comment]
Possibly related to [issue #82](https://github.com/Codeusa/Borderless-Gaming/issues/82).  Try starting Borderless Gaming as an Administrator.

**Comment by Patterner** [comment]
tried the update and no luck so far. 

But 6.5 is using "vendetta.rlb" as the name under Favorites, not just "Vendetta" like 7.x
Using the Process Names menu opion doesn't change anything.

**Comment by psouza4** [comment]
Add it to your favorites by process name, not the default of window title.  It's a right-click option.

**Comment by psouza4** [comment]
I just downloaded Vendetta Online, signed up for an account, installed it, and verified that your issue is identical to issue [issue #82](https://github.com/Codeusa/Borderless-Gaming/issues/82).

Quit out of Borderless Gaming.  From your desktop or using the Start menu (click Start -> All Programs -> Borderless Gaming), find the the shortcut to Borderless Gaming.  Right-click on the shortcut and choose "Run as Administrator".

Vendetta Online runs itself with elevated permissions (UAC) and will need Borderless Gaming to run as an administrator too.

**Comment by Patterner** [comment]
Updated BG and it works now.
